# Generated by Django 4.0 on 2022-02-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0002_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reputation',
            field=models.IntegerField(default=100),
        ),
    ]
