# Generated by Django 4.0 on 2022-02-12 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0004_alter_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='consortium',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=26),
        ),
    ]
