# Generated by Django 4.0.5 on 2022-07-26 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0008_userfollow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
