# Generated by Django 4.0.5 on 2022-08-08 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0011_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reputation_multiplier',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.TextField()),
                ('commented_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ourapp.post')),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
