# Generated by Django 4.0.5 on 2022-08-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0012_user_reputation_multiplier_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.IntegerField(default=0),
        ),
    ]
