# Generated by Django 4.0.5 on 2022-08-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0013_post_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='darkModeOn',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='name_colour',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
